- name: install remi repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    state: installed

- name: enabling redis
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: installing Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: replacing ipaddress from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start & Enable Redis Service
  ansible.builtin.service:
    name: redis
    enabled: yes
    state: started
           
