- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup

- name: copying user.service
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: reloading deamon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enabling and starting user
  ansible.builtin.service:
    name: user
    enabled: yes
    state: started

- name: copying mongo.repo
  ansible.builtin.copy:  
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb-org-shell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: loading schemas
  ansible.builtin.shell: mongo --host 3.91.7.178 </app/schema/user.js         
