- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup

- name: copying cart.service
  ansible.builtin.copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: reloading deamon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enabling and starting cart
  ansible.builtin.service:
    name: cart
    enabled: yes
    state: started